In [218]:
import pandas as pd

In [219]:
df=pd.read_csv(r'/home/carmencuadrado/Ironhack/dataptmad0420/extra-work/m1/Untitled Folder/IMDB-Movie-Data.csv')

In [220]:
##Challenge 1. Warm up

##We want to create bins of movies according to the number of votes they've received. For that matter, we will create a new column named 'bin' which will tag every movie as follow:

    #From 0 to 999 ==> 1
    #From 1000 to 9999 ==> 2
    #From 10000 to 99999 ==> 3
    #From 100000 to 999999 ==> 4
    #More than 1000000 ==> 5

In [221]:
df['Bins']=df['Votes'].apply(lambda x:1 if x<=999 else(2 if x<=9999 else (3 if x<=99999 else (4 if x<=999999 else 5))))

In [222]:
df['Bins'].unique()

array([4, 3, 2, 1, 5])

In [223]:
#Challenge 2. Using axis concept
#We want to know how much is the revenue per minute for every movie.

In [224]:
df['Revenue per minute']=df.apply(lambda x: x['Revenue (Millions)']/x['Runtime (Minutes)'], axis=1)

In [225]:
#Challenge 3. Using the lambda
#We want to create a new ranking where we add 1 point if the genre is thriller but subtract 1 point if the genre is comedy.

In [226]:
df['New_Rank_by_Genre'] = df.apply(lambda x : x['Rank']-1 if 'Comedy' in x['Genre'] else (x['Rank']+1 if 'Thriller' in x['Genre'] else x['Rank']), axis =1)

In [227]:
#Challenge 4. Now the real stuff
#We want to know if the sum of the ASCII value of every character of the movie title divided by the number of votes retrieve a prime number...remember, prime numbers are integers.

In [228]:
df['ascii/value']=df.apply(lambda x: sum([(ord(i)) for i in x['Title']])/x['Votes'], axis=1)

In [229]:
df[df['ascii/value']>=1]['ascii/value'].unique()

array([ 1.17309417,  6.53153153,  1.6959847 ,  1.74273859,  4.08266129,
        3.42293907,  1.13880446,  3.12027491,  2.14453125,  1.38063862,
        6.47752809,  8.08584337, 13.16666667,  3.53101737,  1.152019  ,
        1.37175325,  8.32173913,  9.52447552,  1.02564103, 12.48039216,
        5.17916667, 13.6402439 ,  9.26457399,  8.16818182, 20.29508197,
        6.03780069,  1.30014749,  3.14855072,  1.34960938,  5.34848485,
        1.26342711,  1.15092025,  3.9852071 ,  5.7833935 ,  4.14450867,
        2.59543568,  1.08339173,  3.38081395,  5.23003195,  3.88101983,
        2.34765625,  1.86973948,  5.1005291 ,  2.96808511,  1.14665708,
        1.72543353,  4.68811881,  1.08728522,  1.00974026,  2.66785714])

In [230]:
print('Diving ascii summed values for Titles by Votes yields float numbers. Selecting those who are =>1 I do not see any that could be potentially converted to int, though I conclude that there is not prime numer, as prime numbers are int.')

Diving ascii summed values for Titles by Votes yields float numbers. Selecting those who are =>1 I do not see any that could be potentially converted to int, though I conclude that there is not prime numer, as prime numbers are int.

In [231]:
#Challenge 5. And finally some fantasy
#Feel free to propose your own ranking based in aggregations of at least 3 columns of the dataset.

In [232]:
new_ranking=df[['Title','Rating', 'Votes', 'Revenue (Millions)']].sort_values(['Rating', 'Votes', 'Revenue (Millions)'],ascending=False).reset_index()
new_ranking.index=pd.RangeIndex(len(new_ranking.index))
new_ranking=new_ranking.assign(New_Ranking_by_Votes_Rating_Revenue=new_ranking.index.get_level_values(None))

In [233]:
new_ranking.drop(columns='index')
df=pd.merge(df,new_ranking, left_on='Title', right_on='Title', how='left')
df.drop(columns=['index','Rating_y','Votes_y','Revenue (Millions)_y'], inplace=True)

In [234]:
df.sort_values(by='New_Ranking_by_Votes_Rating_Revenue')

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating_x,Votes_x,Revenue (Millions)_x,Metascore,Bins,Revenue per minute,New_Rank_by_Genre,ascii/value,New_Ranking_by_Votes_Rating_Revenue
54,55,The Dark Knight,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0,5,3.508684,55,0.000754,0
80,81,Inception,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.0,5,1.976824,81,0.000592,1
117,118,Dangal,"Action,Biography,Drama",Former wrestler Mahavir Singh Phogat and his t...,Nitesh Tiwari,"Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...",2016,161,8.8,48969,11.15,NaN,3,0.069255,118,0.011905,2
36,37,Interstellar,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0,5,1.112367,37,0.001215,3
250,250,The Intouchables,"Biography,Comedy,Drama",After he becomes a quadriplegic from a paragli...,Olivier Nakache,"François Cluzet, Omar Sy, Anne Le Ny, Audrey F...",2011,112,8.6,557965,13.18,57.0,4,0.117679,249,0.002814,4
96,97,Kimi no na wa,"Animation,Drama,Fantasy",Two strangers find themselves linked in a biza...,Makoto Shinkai,"Ryûnosuke Kamiki, Mone Kamishiraishi, Ryô Nari...",2016,106,8.6,34110,4.68,79.0,3,0.044151,97,0.033245,5
124,125,The Dark Knight Rises,"Action,Thriller",Eight years after the Joker's reign of anarchy...,Christopher Nolan,"Christian Bale, Tom Hardy, Anne Hathaway,Gary ...",2012,164,8.5,1222645,448.13,78.0,5,2.732500,126,0.001556,6
99,100,The Departed,"Crime,Drama,Thriller",An undercover cop and a mole in the police att...,Martin Scorsese,"Leonardo DiCaprio, Matt Damon, Jack Nicholson,...",2006,151,8.5,937414,132.37,85.0,4,0.876623,101,0.001205,7
64,65,The Prestige,"Drama,Mystery,Sci-Fi",Two stage magicians engage in competitive one-...,Christopher Nolan,"Christian Bale, Hugh Jackman, Scarlett Johanss...",2006,130,8.5,913152,53.08,66.0,4,0.408308,65,0.001266,8
133,134,Whiplash,"Drama,Music",A promising young drummer enrolls at a cut-thr...,Damien Chazelle,"Miles Teller, J.K. Simmons, Melissa Benoist, P...",2014,107,8.5,477276,13.09,88.0,4,0.122336,134,0.001743,9
477,477,The Lives of Others,"Drama,Thriller","In 1984 East Berlin, an agent of the secret po...",Florian Henckel von Donnersmarck,"Ulrich Mühe, Martina Gedeck,Sebastian Koch, Ul...",2006,137,8.5,278103,11.28,89.0,4,0.082336,478,0.006264,10
993,992,Taare Zameen Par,"Drama,Family,Music",An eight-year-old boy is thought to be a lazy ...,Aamir Khan,"Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...",2007,165,8.5,102697,1.20,42.0,4,0.007273,992,0.014178,11
144,145,Django Unchained,"Drama,Western","With the help of a German bounty hunter , a fr...",Quentin Tarantino,"Jamie Foxx, Christoph Waltz, Leonardo DiCaprio...",2012,165,8.4,1039115,162.80,81.0,5,0.986667,145,0.001480,12
636,635,WALL·E,"Animation,Adventure,Family","In the distant future, a small waste-collectin...",Andrew Stanton,"Ben Burtt, Elissa Knight, Jeff Garlin, Fred Wi...",2008,98,8.4,776897,223.81,NaN,4,2.283776,635,0.000716,13
431,431,3 Idiots,"Comedy,Drama",Two friends are searching for their long lost ...,Rajkumar Hirani,"Aamir Khan, Madhavan, Mona Singh, Sharman Joshi",2009,170,8.4,238789,6.52,67.0,4,0.038353,430,0.002944,14
863,862,Koe no katachi,"Animation,Drama,Romance","The story revolves around Nishimiya Shoko, a g...",Naoko Yamada,"Miyu Irino, Saori Hayami, Aoi Yuki, Kenshô Ono",2016,129,8.4,2421,NaN,80.0,2,NaN,862,0.535729,15
77,78,Inglourious Basterds,"Adventure,Drama,War","In Nazi-occupied France during World War II, a...",Quentin Tarantino,"Brad Pitt, Diane Kruger, Eli Roth,Mélanie Laurent",2009,153,8.3,959065,120.52,69.0,4,0.787712,78,0.002127,16
500,500,Up,"Animation,Adventure,Comedy",Seventy-eight year old Carl Fredricksen travel...,Pete Docter,"Edward Asner, Jordan Nagai, John Ratzenberger,...",2009,96,8.3,722203,292.98,88.0,4,3.051875,499,0.000273,17
690,689,Toy Story 3,"Animation,Adventure,Comedy",The toys are mistakenly delivered to a day-car...,Lee Unkrich,"Tom Hanks, Tim Allen, Joan Cusack, Ned Beatty",2010,103,8.3,586669,414.98,92.0,4,4.028932,688,0.001664,18
6,7,La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0,4,1.180156,6,0.003066,19
456,456,Jagten,Drama,"A teacher lives a lonely life, all the while s...",Thomas Vinterberg,"Mads Mikkelsen, Thomas Bo Larsen, Annika Wedde...",2012,115,8.3,192263,0.61,76.0,4,0.005304,456,0.003126,20
26,27,Bahubali: The Beginning,"Action,Adventure,Drama","In ancient India, an adventurous and daring ma...",S.S. Rajamouli,"Prabhas, Rana Daggubati, Anushka Shetty,Tamann...",2015,159,8.3,76193,6.50,NaN,3,0.040881,27,0.027772,21
479,479,Paint It Black,Drama,A young woman attempts to deal with the death ...,Amber Tamblyn,"Alia Shawkat, Nancy Kwan, Annabelle Attanasio,...",2016,96,8.3,61,NaN,71.0,1,NaN,479,20.295082,22
82,83,The Wolf of Wall Street,"Biography,Comedy,Crime","Based on the true story of Jordan Belfort, fro...",Martin Scorsese,"Leonardo DiCaprio, Jonah Hill, Margot Robbie,M...",2013,180,8.2,865134,116.87,75.0,4,0.649278,82,0.002392,23
647,646,Gran Torino,Drama,Disgruntled Korean War veteran Walt Kowalski s...,Clint Eastwood,"Clint Eastwood, Bee Vang, Christopher Carley,A...",2008,116,8.2,595779,148.09,NaN,4,1.276638,646,0.001778,24
230,231,Pan's Labyrinth,"Drama,Fantasy,War","In the falangist Spain of 1944, the bookish yo...",Guillermo del Toro,"Ivana Baquero, Ariadna Gil, Sergi López,Maribe...",2006,118,8.2,498879,37.62,98.0,4,0.318814,231,0.002834,25
242,242,Inside Out,"Animation,Adventure,Comedy",After young Riley is uprooted from her Midwest...,Pete Docter,"Amy Poehler, Bill Hader, Lewis Black, Mindy Ka...",2015,95,8.2,416689,356.45,94.0,4,3.752105,241,0.002275,26
194,195,Warrior,"Action,Drama,Sport",The youngest son of an alcoholic former boxer ...,Gavin O'Connor,"Tom Hardy, Nick Nolte, Joel Edgerton, Jennifer...",2011,140,8.2,355722,13.65,71.0,4,0.097500,195,0.002086,27
143,144,Room,Drama,A young boy is raised within the confines of a...,Lenny Abrahamson,"Brie Larson, Jacob Tremblay, Sean Bridgers,Wen...",2015,118,8.2,224132,14.68,86.0,4,0.124407,144,0.001843,28
16,17,Hacksaw Ridge,"Biography,Drama,History","WWII American Army Medic Desmond T. Doss, who ...",Mel Gibson,"Andrew Garfield, Sam Worthington, Luke Bracey,...",2016,139,8.2,211760,67.12,71.0,4,0.482878,17,0.005804,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
779,778,Final Girl,"Action,Thriller",A man teaches a young woman how to become a co...,Tyler Shields,"Abigail Breslin, Wes Bentley, Logan Huffman,Al...",2015,90,4.7,9026,NaN,56.0,2,NaN,779,0.101928,970
913,912,I Am the Pretty Thing That Lives in the House,Thriller,A young nurse takes care of elderly author who...,Oz Perkins,"Ruth Wilson, Paula Prentiss, Lucy Boynton, Bob...",2016,87,4.7,4204,NaN,68.0,2,NaN,913,0.946242,971
523,523,Viking,"Action,Drama,History","Kievan Rus, late 10th century. After the death...",Andrey Kravchuk,"Anton Adasinsky, Aleksandr Armer, Vilen Babich...",2016,133,4.7,1830,23.05,57.0,2,0.173308,523,0.336612,972
27,28,Dead Awake,"Horror,Thriller",A young woman must save herself and her friend...,Phillip Guzman,"Jocelin Donahue, Jesse Bradford, Jesse Borrego...",2016,99,4.7,523,0.01,NaN,1,0.000101,29,1.695985,973
556,556,The Boy Next Door,"Mystery,Thriller","A woman, separated from her unfaithful husband...",Rob Cohen,"Jennifer Lopez, Ryan Guzman, Kristin Chenoweth...",2015,91,4.6,30180,35.39,30.0,3,0.388901,557,0.049768,974
789,788,Max Steel,"Action,Adventure,Family",The adventures of teenager Max McGrath and his...,Stewart Hendler,"Ben Winchell, Josh Brener, Maria Bello, Andy G...",2016,92,4.6,11555,3.77,22.0,3,0.040978,788,0.072263,975
828,827,Shut In,"Drama,Horror,Thriller",A heart-pounding thriller about a widowed chil...,Farren Blackburn,"Naomi Watts, Charlie Heaton, Jacob Tremblay,Ol...",2016,91,4.6,5715,6.88,NaN,2,0.075604,828,0.111111,976
821,820,Wolves at the Door,"Horror,Thriller",Four friends gather at an elegant home during ...,John R. Leonetti,"Katie Cassidy, Elizabeth Henstridge, Adam Camp...",2016,73,4.6,564,NaN,63.0,1,NaN,821,2.968085,977
748,747,Only for One Night,Thriller,A married womans husband with a perfect life c...,Chris Stokes,"Brian White, Karrueche Tran, Angelique Pereira...",2016,86,4.6,313,NaN,60.0,1,NaN,748,5.230032,978
773,772,The Assignment,"Action,Crime,Thriller",After waking up and discovering that he has un...,Walter Hill,"Sigourney Weaver, Michelle Rodriguez, Tony Sha...",2016,95,4.5,2043,NaN,34.0,2,NaN,773,0.670582,979
938,937,The Human Centipede (First Sequence),Horror,A mad scientist kidnaps and mutilates a trio o...,Tom Six,"Dieter Laser, Ashley C. Williams, Ashlynn Yenn...",2009,92,4.4,60655,0.18,33.0,3,0.001957,937,0.053763,980
553,553,Fantastic Four,"Action,Adventure,Sci-Fi",Four young outsiders teleport to an alternate ...,Josh Trank,"Miles Teller, Kate Mara, Michael B. Jordan, Ja...",2015,100,4.3,121847,56.11,27.0,4,0.561100,553,0.011235,981
509,509,Movie 43,"Comedy,Romance",A series of interconnected short films follows...,Elizabeth Banks,"Emma Stone, Stephen Merchant, Richard Gere, Li...",2013,94,4.3,83625,8.83,18.0,3,0.093936,508,0.007737,982
954,953,Sex and the City 2,"Comedy,Drama,Romance","While wrestling with the pressures of life, lo...",Michael Patrick King,"Sarah Jessica Parker, Kim Cattrall, Kristin Da...",2010,146,4.3,62403,95.33,27.0,3,0.652945,952,0.024342,983
802,801,Yoga Hosers,"Comedy,Fantasy,Horror",Two teenage yoga enthusiasts team up with a le...,Kevin Smith,"Lily-Rose Depp, Harley Quinn Smith, Johnny Dep...",2016,88,4.3,7091,NaN,23.0,2,NaN,800,0.149485,984
582,582,The Last Airbender,"Action,Adventure,Family","Follows the adventures of Aang, a young succes...",M. Night Shyamalan,"Noah Ringer, Nicola Peltz, Jackson Rathbone,De...",2010,103,4.2,125129,NaN,20.0,4,NaN,582,0.013306,985
840,839,Exposed,"Crime,Drama,Mystery",A police detective investigates the truth behi...,Gee Malik Linton,"Ana de Armas, Keanu Reeves, Christopher McDona...",2016,102,4.2,8409,NaN,23.0,2,NaN,839,0.086574,986
63,64,Fifty Shades of Grey,"Drama,Romance,Thriller",Literature student Anastasia Steele's life cha...,Sam Taylor-Johnson,"Dakota Johnson, Jamie Dornan, Jennifer Ehle,El...",2015,125,4.1,244474,166.15,46.0,4,1.329200,65,0.007485,987
617,617,2307: Winter's Dream,Sci-Fi,"In 2307, a future soldier is sent on a mission...",Joey Curtis,"Paul Sidhu, Branden Coles, Arielle Holmes, Kel...",2016,101,4.0,277,20.76,53.0,1,0.205545,617,5.783394,988
237,238,The Disappointments Room,"Drama,Horror,Thriller",A mother and her young son release unimaginabl...,D.J. Caruso,"Kate Beckinsale, Mel Raido, Duncan Joiner, Luc...",2016,85,3.9,4895,2.41,31.0,2,0.028353,239,0.483759,989
526,526,Birth of the Dragon,"Action,Biography,Drama","Young, up-and-coming martial artist, Bruce Lee...",George Nolfi,"Billy Magnussen, Terry Chen, Teresa Navarro,Va...",2016,103,3.9,552,93.05,61.0,1,0.903398,526,3.148551,990
402,402,The Black Room,Horror,PAUL and JENNIFER HEMDALE have just moved into...,Rolfe Kanefsky,"Natasha Henstridge, Lukas Hassel, Lin Shaye,Do...",2016,91,3.9,240,NaN,71.0,1,NaN,402,5.179167,991
270,270,Satanic,Horror,Four friends on their way to Coachella stop of...,Jeffrey G. Hunt,"Sarah Hyland, Steven Krueger, Justin Chon, Cla...",2016,85,3.7,2384,NaN,NaN,2,NaN,270,0.296560,992
49,50,The Last Face,Drama,A director (Charlize Theron) of an internation...,Sean Penn,"Charlize Theron, Javier Bardem, Adèle Exarchop...",2016,130,3.7,987,NaN,16.0,1,NaN,50,1.138804,993
970,969,Wrecker,"Action,Horror,Thriller",Best friends Emily and Lesley go on a road tri...,Micheal Bafaro,"Anna Hutchison, Andrea Whitburn, Jennifer Koen...",2015,83,3.5,1210,NaN,37.0,2,NaN,970,0.597521,994
892,891,The Intent,"Crime,Drama",Gunz (Dylan Duffus) is thrust into a world of ...,Femi Oyeniran,"Dylan Duffus, Scorcher,Shone Romulus, Jade Asha",2016,104,3.5,202,NaN,59.0,1,NaN,891,4.688119,995
649,648,Tall Men,"Fantasy,Horror,Thriller",A challenged man is stalked by tall phantoms i...,Jonathan Holbrook,"Dan Crisafulli, Kay Whitney, Richard Garcia, P...",2016,133,3.2,173,NaN,57.0,1,NaN,649,4.144509,996
873,872,Dragonball Evolution,"Action,Adventure,Fantasy",The young warrior Son Goku sets out on a quest...,James Wong,"Justin Chatwin, James Marsters, Yun-Fat Chow, ...",2009,85,2.7,59512,9.35,45.0,3,0.110000,872,0.033792,997
42,43,Don't Fuck in the Woods,Horror,A group of friends are going on a camping trip...,Shawn Burkett,"Brittany Blanton, Ayse Howard, Roman Jossart,N...",2016,73,2.7,496,NaN,NaN,1,NaN,43,4.082661,998
831,830,Disaster Movie,Comedy,"Over the course of one evening, an unsuspectin...",Jason Friedberg,"Carmen Electra, Vanessa Lachey,Nicole Parker, ...",2008,87,1.9,77207,14.17,15.0,3,0.162874,829,0.017809,999

In [235]:
#Challenge 6. Freaky bonus
#We want to know which movies might have hidden paterns in their description. A way to know that is finding those movies which the sum of all numeric values of the string description hash (SHA256) are between their revenue and their number of votes.